# Generated by Django 4.1.1 on 2022-11-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(max_length=500),
        ),
    ]
